### PR TITLE
[DOC] Revisions to README.md

### PR DESCRIPTION
**Pull request by BurdetteLamar**
Updates:
- Usage:  now points to the main class.
- Installation:  deleted (no longer needed).

### CODE REVIEW

**Review by peterzhu2118 — CHANGES_REQUESTED** [review]
While I'm all for refactoring/rewriting the README, I'm not a fan of deleting a large chunk of it. The README is the first document a user sees when they navigate to this repo, so it should describe what this library is, how to install it, and a quick start guide that highlights the most common ways to use this library (and perhaps linking to separate documentation for more advanced things).

**Comment by BurdetteLamar** [comment]
> While I'm all for refactoring/rewriting the README, I'm not a fan of deleting a large chunk of it. The README is the first document a user sees when they navigate to this repo, so it should describe what this library is, how to install it, and a quick start guide that highlights the most common ways to use this library (and perhaps linking to separate documentation for more advanced things).

I'll be happy to restore the Usage section.  The Installation section should remain deleted?  Along with the remark about installation in the Development section?

**Comment by peterzhu2118** [comment]
I think the Installation and Usage sections should be kept (or rewritten). I also think the blurb at the beginning should be expanded, IMO the one-liner is a bit too simple. The other parts I'm ok with deleting.

**Comment by BurdetteLamar** [comment]
> I think the Installation and Usage sections should be kept (or rewritten). I also think the blurb at the beginning should be expanded, IMO the one-liner is a bit too simple. The other parts I'm ok with deleting.

Re Installation:  Doesn't Net::HTTP come with Ruby nowadays?  So no installation needed?

**Comment by peterzhu2118** [comment]
Yes, it's bundled with Ruby, but it might not be the latest version, in which case they'll have to install it from RubyGems.

**Comment by BurdetteLamar** [comment]
Stet, then.

**Pull request closed without merging**
