### PR TITLE
Net::HTTPResponse nil checking

### PR DESCRIPTION
**Pull request by BrianHawley**
Fix nil handling in read_body and stream_check.

Fixes: #70

### CODE REVIEW

**Comment by BrianHawley** [comment]
@nobu or @jeremyevans what do you think? The tests pass locally. Just improving error handling.

**Comment by jeremyevans** [comment]
The `stream_check` change looks fine. It's questionable whether `body` should return `nil` or an empty string in such an error case.  That's probably a decision that @nurse should make.

**Comment by BrianHawley** [comment]
@jeremyevans if it should return an empty string, then we should assign the empty string a few lines above instead of assigning nil. At that point, the line I added can be removed and the test can be adjusted accordingly.

**Comment by BrianHawley** [comment]
@jeremyevans and @nurse what do I need to do to get this moving forward? Should I split the `read_body` and `stream_check` changes into separate PRs? I made this PR in September, so I'm interested in getting this in.

**Comment by jeremyevans** [comment]
@BrianHawley  I don't think there is more you can do. @hsbt @nobu Can either of you review/merge this?

**Comment by BrianHawley** [comment]
Can this get merged in time to get it into Ruby 3.3? I made sure to make the PR in time for it to get into Ruby 3.2.

**Pull request merged**
